FROM rockylinux:9.3@sha256:d7be1c094cc5845ee815d4632fe377514ee6ebcf8efaed6892889657e5ddaaa6

RUN dnf -y install glib2-devel gtk3-devel atk-devel \
    platform-python-devel \
    findutils \
    wget xz make \
    git \
    gcc
