FROM rockylinux:8.9@sha256:9794037624aaa6212aeada1d28861ef5e0a935adaf93e4ef79837119f2a2d04c

RUN dnf -y install glib2-devel gtk3-devel atk-devel \
    platform-python-devel \
    findutils \
    wget xz make \
    git \
    gcc
